# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements
Content-Type: application/json
# Authorization: Token dfbb34e348107987dba9f1440196e79aef431f6e
# Authorization: Token 28bc78478ffb6fc900bcd12d92892cbe301e7066
Authorization: Token b0a0c7d418ee5c51d4bd3b65d8ac3e0371bbb971
# Authorization: Token 3c9363198a3d0a177402c88ffad661ba70f533e5

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token dfbb34e348107987dba9f1440196e79aef431f6e
# Authorization: Token 28bc78478ffb6fc900bcd12d92892cbe301e7066
# Authorization: Token b0a0c7d418ee5c51d4bd3b65d8ac3e0371bbb971
# Authorization: Token 3c9363198a3d0a177402c88ffad661ba70f533e5

{
  "title": "Шкаф 1",
  "description": "admin"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/99/
Content-Type: application/json
# Authorization: Token dfbb34e348107987dba9f1440196e79aef431f6e
# Authorization: Token 28bc78478ffb6fc900bcd12d92892cbe301e7066
# Authorization: Token b0a0c7d418ee5c51d4bd3b65d8ac3e0371bbb971
Authorization: Token 3c9363198a3d0a177402c88ffad661ba70f533e5

# {
#   "status": "OPEN"
# }

# {
#   "status": "CLOSED"
# }

{
  "status": "DRAFT"
}

###

# удаление объявления
DELETE {{baseUrl}}/advertisements/102/
Content-Type: application/json
# Authorization: Token dfbb34e348107987dba9f1440196e79aef431f6e
Authorization: Token 28bc78478ffb6fc900bcd12d92892cbe301e7066
# Authorization: Token b0a0c7d418ee5c51d4bd3b65d8ac3e0371bbb971
# Authorization: Token 3c9363198a3d0a177402c88ffad661ba70f533e5


###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json
# Authorization: Token dfbb34e348107987dba9f1440196e79aef431f6e

###

# фильтрация по дате ???
GET {{baseUrl}}/advertisements/?created_at=2023-04-01
Content-Type: application/json

###

# фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=DRAFT
Content-Type: application/json
# Authorization: Token dfbb34e348107987dba9f1440196e79aef431f6e

###

# поиск по названию ???
GET {{baseUrl}}/advertisements/?search=9999
Content-Type: application/json
# Authorization: Token dfbb34e348107987dba9f1440196e79aef431f6e

###

# добавить в избранное ???
POST {{baseUrl}}/advertisements/mark-as-favourite/101
Content-Type: application/json
# Authorization: Token dfbb34e348107987dba9f1440196e79aef431f6e
Authorization: Token 28bc78478ffb6fc900bcd12d92892cbe301e7066
# Authorization: Token b0a0c7d418ee5c51d4bd3b65d8ac3e0371bbb971
# Authorization: Token 3c9363198a3d0a177402c88ffad661ba70f533e5

{
  "creator": "admin"
}