# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements
Content-Type: application/json
# Authorization: Token 31143a999775a89cba1a2afb25bb649711688e98
# Authorization: Token 4bad2b2e8ee67352d1a6dd6bd5bea185b086c840
# Authorization: Token 1f06789f139e88ed9b631ec1cf43138cee90eb2f

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 31143a999775a89cba1a2afb25bb649711688e98
# Authorization: Token 4bad2b2e8ee67352d1a6dd6bd5bea185b086c840

{
  "title": "Шкаф IKEA111",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/34/
Content-Type: application/json
Authorization: Token 31143a999775a89cba1a2afb25bb649711688e98
# Authorization: Token 4bad2b2e8ee67352d1a6dd6bd5bea185b086c840


{
  "status": "CLOSED"
}
###

# удаление объявления
DELETE {{baseUrl}}/advertisements/2/
Content-Type: application/json
# Authorization: Token 31143a999775a89cba1a2afb25bb649711688e98
Authorization: Token 4bad2b2e8ee67352d1a6dd6bd5bea185b086c840

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at=2023-04-01
Content-Type: application/json

###

# фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=OPEN
Content-Type: application/json

###

# поиск по названию
GET {{baseUrl}}/advertisements/?search=9999
Content-Type: application/json
